#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countSwaps function below.
def countSwaps(a):
    isSorted = False
    counter=0
    while(isSorted!=True):
        isSorted = True
        for i in range(0,n-1):
            if(a[i]>a[i+1]):
                temp = a[i]
                a[i] = a[i+1]
                a[i+1] = temp
                isSorted = False
                counter+=1
    print("Array is sorted in "+str(counter)+" swaps.")
    print("First Element: "+str(a[0]))
    print("Last Element: "+str(a[-1]))
if __name__ == '__main__':
    n = int(input())

    a = list(map(int, input().rstrip().split()))

    countSwaps(a)
