#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter

# Complete the makeAnagram function below.
def makeAnagram(a, b):

    freq_a = Counter(a)
    freq_b = Counter(b)
    
    elemNotInb = (freq_a - freq_b)
    elemNotIna = (freq_b - freq_a)   
    new_dict = elemNotIna + elemNotInb
    no_of_deletions = sum(new_dict.values())
    
    return no_of_deletions
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = input()

    b = input()

    res = makeAnagram(a, b)

    fptr.write(str(res) + '\n')

    fptr.close()
